apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --config-file=/etc/etcd/etcd-config.yaml
    image: gcr.io/google_containers/etcd-amd64:3.1.11
    ports:
      - containerPort: 12379
        hostPort: 12379
        name: etcd-port
      - containerPort: 12380
        hostPort: 12380
        name: etcd-cl-port
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 10.26.24.77
        path: /health
        port: 12379
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/etcd/etcd-config.yaml
      name: etcd-conf
  hostNetwork: true
  volumes:
  - hostPath:
      path: /k8s/app/etcd/data
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /k8s/conf/etcd-config.yaml
      type: FileOrCreate
    name: etcd-conf
status: {}
