apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --leader-elect=true
    - --controllers=*,bootstrapsigner,tokencleaner
    - --master=http://10.26.24.77:18080
    image: gcr.io/google_containers/kube-controller-manager-amd64:v1.9.2
    ports:
      - containerPort: 10252
        hostPort: 10252
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 10.26.24.77
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
  hostNetwork: true
  volumes:
  - hostPath:
      path: /k8s/app/kube-controller/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
status: {}
